name: diariodesaude
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Black.ttf
        - asset: assets/fonts/Vollkorn-BlackItalic.ttf
        - asset: assets/fonts/Vollkorn-Bold.ttf
        - asset: assets/fonts/Vollkorn-BoldItalic.ttf
        - asset: assets/fonts/Vollkorn-ExtraBold.ttf
        - asset: assets/fonts/Vollkorn-ExtraBoldItalic.ttf
        - asset: assets/fonts/Vollkorn-Italic.ttf
        - asset: assets/fonts/Vollkorn-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Vollkorn-Medium.ttf
        - asset: assets/fonts/Vollkorn-MediumItalic.ttf
        - asset: assets/fonts/Vollkorn-Regular.ttf
        - asset: assets/fonts/Vollkorn-SemiBold.ttf
        - asset: assets/fonts/Vollkorn-SemiBoldItalic.ttf
        - asset: assets/fonts/Vollkorn-VariableFont_wght.ttf
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
    - family: DellaRespira
      fonts:
        - asset: assets/fonts/DellaRespira-Regular.ttf
    - family: Voltaire
      fonts:
        - asset: assets/fonts/Voltaire-Regular.ttf

  assets:
    - assets/images/sapatoverde.png
    - assets/images/sapatos.png
    - assets/images/copoagua.png
    - assets/images/lua.png
    - assets/images/remedio.png
    - assets/images/bemestar.png
    - assets/images/saude.png
    - assets/images/3dmedica.png
    - assets/images/lara.png
    - assets/images/maca.png
    - assets/images/medasiat.png
    - assets/images/medasiat2.png
    - assets/images/medasiatCORT.png
    - assets/images/medasiat2COR.png
    - assets/images/engrenagem.png
    - assets/images/engrenagemM.png
    - assets/images/perfil.png
    - assets/images/coracao.png
