// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuH84DxHMOxbmE4zCFSAAgWNNMt4WMOVc',
    appId: '1:43789366260:web:eeb0768a3da45eef0e7fa1',
    messagingSenderId: '43789366260',
    projectId: 'dosemed-17d2a',
    authDomain: 'dosemed-17d2a.firebaseapp.com',
    storageBucket: 'dosemed-17d2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoDNVbXcs46luoyDnJTcziq7A9ak9BDc',
    appId: '1:43789366260:android:31bf5a11aee2044d0e7fa1',
    messagingSenderId: '43789366260',
    projectId: 'dosemed-17d2a',
    storageBucket: 'dosemed-17d2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnI9wbYwSVSoZgEUtKIHYKGqjgGzg6GIs',
    appId: '1:43789366260:ios:45f64aef5c52ae700e7fa1',
    messagingSenderId: '43789366260',
    projectId: 'dosemed-17d2a',
    storageBucket: 'dosemed-17d2a.firebasestorage.app',
    iosBundleId: 'com.example.diariosaude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnI9wbYwSVSoZgEUtKIHYKGqjgGzg6GIs',
    appId: '1:43789366260:ios:45f64aef5c52ae700e7fa1',
    messagingSenderId: '43789366260',
    projectId: 'dosemed-17d2a',
    storageBucket: 'dosemed-17d2a.firebasestorage.app',
    iosBundleId: 'com.example.diariosaude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuH84DxHMOxbmE4zCFSAAgWNNMt4WMOVc',
    appId: '1:43789366260:web:41a49a8327dba5790e7fa1',
    messagingSenderId: '43789366260',
    projectId: 'dosemed-17d2a',
    authDomain: 'dosemed-17d2a.firebaseapp.com',
    storageBucket: 'dosemed-17d2a.firebasestorage.app',
  );
}
